#!/bin/bash

cd /
cd /home/addweb/first
docker stop helloworld
docker rm helloworld
docekr build -t hello-world /home/addweb/first
docker run -d --name helloworld -p 80:80 -v /home/addweb/first/src/:/var/www/html hello-world
